### ISSUE TITLE
Screen dimensions in recorded gifs do not match with original screen dimensions

### ISSUE THREAD

**Issue by rootingbill** [cmksoftdev/GifRecorder#2]
When attempting to record certain screen dimensions on my screen (3440x2180, DPI scaling of 225%) the recorded dimensions do not match with the original screen dimensions. Please fix or hanzo will track you down 💯 

![tenor](https://user-images.githubusercontent.com/1809834/36613840-ff55cdc8-18da-11e8-9434-96d096f64407.gif)

**Comment by cmk1988** [comment]
Dear master of hanzos,

the bug should be fixed now. Please let me know if it works or not.

Thank you very much.

MfG Chris
